title: Closed Thought
author: Insan Jati
email: insanjati@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Enjoying busy-mind, learn long and prosper.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
